spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: hangyeol
    password: qorgksruf123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port : 6379

logging:
  level:
    org:
      springframework:
        security: DEBUG

