spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: hangyeol
    password: qorgksruf123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port : 6379

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

